import type { NextPage } from "next";
import Head from "next/head";
import SearchBar from "../components/SearchBar";
import ZipcodeResult from "../components/ZipcodeResult";
import AppProvider from "../providers/appProvider";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Zipcode lookup</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <AppProvider>
        <main className={styles.main}>
          <SearchBar />
          <ZipcodeResult />
        </main>
      </AppProvider>

      <footer className={styles.footer}>
        <a href="https://www.linkedin.com/in/alangrosz/" target="_blank" rel="noopener noreferrer">
          Powered by Alan Grosz
        </a>
      </footer>
    </div>
  );
};

export default Home;
